"""move language to project, restrict lookup category

Revision ID: 280983564658
Revises: 18004186fcfc
Create Date: 2026-07-30 00:26:51.502071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280983564658'
down_revision = '18004186fcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
